# Where things are
source:       .
destination:  ./_site
plugins:      ./_plugins
layouts:      ./_layouts
paginate:     8

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false

# Conversion
markdown:     kramdown
highlighter:  rouge
lsi:          false
excerpt_separator: "\n\n"

# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null


#Site config
title: Legendlc
description: Yet Another Jekyll Blog
keywords: My blog
url: ""
feed: /atom.xml
favicon: /images/shortcut.jpg

#Nav config
nav:
  - text: 首页
    url: /index.html
  - text: 分类目录
    url: /categories.html
  - text: 文章归档
    url: /archives.html
  - text: 关于我
    url: /about.html
  - text: 友情链接
    url: /links.html

#Author config
author:
    name: legendlc
    email: llc_legend@163.com
    imageLink: /images/header.jpg
    simpleIntro: One day, I will...
    detailIntro:
      <p>Looking for a job...</p>
      <p></p>

#Follow me, you can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: icon-rss
    url: /atom.xml
  - class: icon-weibo
    url: https://weibo.com/
  - class: icon-facebook
    url: https://facebook.com/
  - class: icon-github-alt
    url: https://github.com/legendlc/
  - class: icon-twitter
    url: https://twitter.com/

#Links
customLinks:
  - item:
    - text: zJiaJun
      url: http://9leg.com/
    - text: Jekyll
      url: http://jekyllrb.com
    - text: Jekyll Theme
      url: https://rubygems.org/search?utf8=%E2%9C%93&query=jekyll-theme
    - text: duoshuo
      url: https://duoshuo.com/
    - text: Baidu tongji
      url: https://tongji.baidu.com
    message: Friends
  - item:
    - text: Markdown tutorial
      url: http://www.appinn.com/markdown/basic.html
    message: Tutorials

#googleAnaly, your id link UA-12345678-X
googleAnaly:
  config: false
  id:

#baidu tongji
baiduTongji:
  config: true
  id: de215d861932c7375aece2a351580091

#comment config
disqus:
  config: false
  id:

duoshuo:
  config: true
  id: legendlc

#baidu share config
baiduShare:
  config: true
